# Generated by Django 3.2.6 on 2023-05-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_conditions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conditions',
            options={'verbose_name_plural': 'Terms and Conditions'},
        ),
        migrations.AlterModelOptions(
            name='uploadedfile',
            options={'verbose_name_plural': 'Uploaded PDF Files'},
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='files/'),
        ),
    ]
