# Generated by Django 3.2.6 on 2023-05-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20230517_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='color',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='width',
            field=models.IntegerField(),
        ),
    ]
