# Generated by Django 3.2.6 on 2023-05-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20230517_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
