# Generated by Django 3.2.6 on 2023-05-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_uploadedfile_converted'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='file_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='image_name',
            field=models.CharField(max_length=210, null=True),
        ),
    ]
