# Generated by Django 3.2.6 on 2023-05-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20230519_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='image_name',
            field=models.CharField(blank=True, max_length=210, null=True),
        ),
    ]
