# Generated by Django 3.2.6 on 2023-05-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20230519_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='converted_files/'),
        ),
    ]
