# Generated by Django 3.2.6 on 2023-05-17 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_auto_token_token_auth_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='token',
            options={'verbose_name_plural': 'Tokens'},
        ),
    ]
